services:
  db:
    image: postgres:15.4
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=quicksign
      - POSTGRES_USER=quicksign
      - POSTGRES_PASSWORD=123@456
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quicksign -d quicksign"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "127.0.0.1:5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: redis:7
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  redis-data: